<?php

/**
 * BaseScssPeriod
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $label
 * @property time $start_time
 * @property time $end_time
 * @property boolean $tte
 * @property integer $week_id
 * @property ScssWeek $Week
 * @property Doctrine_Collection $ScssClass
 * 
 * @method string              getLabel()      Returns the current record's "label" value
 * @method time                getStartTime()  Returns the current record's "start_time" value
 * @method time                getEndTime()    Returns the current record's "end_time" value
 * @method boolean             getTte()        Returns the current record's "tte" value
 * @method integer             getWeekId()     Returns the current record's "week_id" value
 * @method ScssWeek            getWeek()       Returns the current record's "Week" value
 * @method Doctrine_Collection getScssClass()  Returns the current record's "ScssClass" collection
 * @method ScssPeriod          setLabel()      Sets the current record's "label" value
 * @method ScssPeriod          setStartTime()  Sets the current record's "start_time" value
 * @method ScssPeriod          setEndTime()    Sets the current record's "end_time" value
 * @method ScssPeriod          setTte()        Sets the current record's "tte" value
 * @method ScssPeriod          setWeekId()     Sets the current record's "week_id" value
 * @method ScssPeriod          setWeek()       Sets the current record's "Week" value
 * @method ScssPeriod          setScssClass()  Sets the current record's "ScssClass" collection
 * 
 * @package    scss
 * @subpackage model
 * @author     David Durost
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseScssPeriod extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('scss_period');
        $this->hasColumn('label', 'string', 25, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 25,
             ));
        $this->hasColumn('start_time', 'time', null, array(
             'type' => 'time',
             'notnull' => true,
             ));
        $this->hasColumn('end_time', 'time', null, array(
             'type' => 'time',
             'notnull' => true,
             ));
        $this->hasColumn('tte', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('week_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ScssWeek as Week', array(
             'local' => 'week_id',
             'foreign' => 'id'));

        $this->hasMany('ScssClass', array(
             'local' => 'id',
             'foreign' => 'period_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'label',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}