<?php

/**
 * BaseScssCourse
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $label
 * @property integer $meritbadge_id
 * @property integer $camp_id
 * @property ScssMeritBadge $MeritBadge
 * @property ScssCamp $Camp
 * @property Doctrine_Collection $ScssClass
 * 
 * @method string              getLabel()         Returns the current record's "label" value
 * @method integer             getMeritbadgeId()  Returns the current record's "meritbadge_id" value
 * @method integer             getCampId()        Returns the current record's "camp_id" value
 * @method ScssMeritBadge      getMeritBadge()    Returns the current record's "MeritBadge" value
 * @method ScssCamp            getCamp()          Returns the current record's "Camp" value
 * @method Doctrine_Collection getScssClass()     Returns the current record's "ScssClass" collection
 * @method ScssCourse          setLabel()         Sets the current record's "label" value
 * @method ScssCourse          setMeritbadgeId()  Sets the current record's "meritbadge_id" value
 * @method ScssCourse          setCampId()        Sets the current record's "camp_id" value
 * @method ScssCourse          setMeritBadge()    Sets the current record's "MeritBadge" value
 * @method ScssCourse          setCamp()          Sets the current record's "Camp" value
 * @method ScssCourse          setScssClass()     Sets the current record's "ScssClass" collection
 * 
 * @package    scss
 * @subpackage model
 * @author     David Durost
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseScssCourse extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('scss_course');
        $this->hasColumn('label', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
        $this->hasColumn('meritbadge_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('camp_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ScssMeritBadge as MeritBadge', array(
             'local' => 'meritbadge_id',
             'foreign' => 'id'));

        $this->hasOne('ScssCamp as Camp', array(
             'local' => 'camp_id',
             'foreign' => 'id'));

        $this->hasMany('ScssClass', array(
             'local' => 'id',
             'foreign' => 'course_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'label',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}