<?php

/**
 * BaseScssCabin
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $max
 * @property integer $camp_id
 * @property ScssCamp $Camp
 * @property Doctrine_Collection $ScssStaff
 * 
 * @method string              getName()      Returns the current record's "name" value
 * @method integer             getMax()       Returns the current record's "max" value
 * @method integer             getCampId()    Returns the current record's "camp_id" value
 * @method ScssCamp            getCamp()      Returns the current record's "Camp" value
 * @method Doctrine_Collection getScssStaff() Returns the current record's "ScssStaff" collection
 * @method ScssCabin           setName()      Sets the current record's "name" value
 * @method ScssCabin           setMax()       Sets the current record's "max" value
 * @method ScssCabin           setCampId()    Sets the current record's "camp_id" value
 * @method ScssCabin           setCamp()      Sets the current record's "Camp" value
 * @method ScssCabin           setScssStaff() Sets the current record's "ScssStaff" collection
 * 
 * @package    scss
 * @subpackage model
 * @author     David Durost
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseScssCabin extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('scss_cabin');
        $this->hasColumn('name', 'string', 60, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 60,
             ));
        $this->hasColumn('max', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('camp_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ScssCamp as Camp', array(
             'local' => 'camp_id',
             'foreign' => 'id'));

        $this->hasMany('ScssStaff', array(
             'local' => 'id',
             'foreign' => 'cabin_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}