<?php

/**
 * BaseScssWeek
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $label
 * @property timestamp $start_date
 * @property timestamp $end_date
 * @property boolean $tte
 * @property integer $camp_id
 * @property ScssCamp $Camp
 * @property Doctrine_Collection $ScssPeriod
 * @property ScssTroopRotation $ScssTroopRotation
 * @property Doctrine_Collection $ScssTroopEnrollment
 * 
 * @method string              getLabel()               Returns the current record's "label" value
 * @method timestamp           getStartDate()           Returns the current record's "start_date" value
 * @method timestamp           getEndDate()             Returns the current record's "end_date" value
 * @method boolean             getTte()                 Returns the current record's "tte" value
 * @method integer             getCampId()              Returns the current record's "camp_id" value
 * @method ScssCamp            getCamp()                Returns the current record's "Camp" value
 * @method Doctrine_Collection getScssPeriod()          Returns the current record's "ScssPeriod" collection
 * @method ScssTroopRotation   getScssTroopRotation()   Returns the current record's "ScssTroopRotation" value
 * @method Doctrine_Collection getScssTroopEnrollment() Returns the current record's "ScssTroopEnrollment" collection
 * @method ScssWeek            setLabel()               Sets the current record's "label" value
 * @method ScssWeek            setStartDate()           Sets the current record's "start_date" value
 * @method ScssWeek            setEndDate()             Sets the current record's "end_date" value
 * @method ScssWeek            setTte()                 Sets the current record's "tte" value
 * @method ScssWeek            setCampId()              Sets the current record's "camp_id" value
 * @method ScssWeek            setCamp()                Sets the current record's "Camp" value
 * @method ScssWeek            setScssPeriod()          Sets the current record's "ScssPeriod" collection
 * @method ScssWeek            setScssTroopRotation()   Sets the current record's "ScssTroopRotation" value
 * @method ScssWeek            setScssTroopEnrollment() Sets the current record's "ScssTroopEnrollment" collection
 * 
 * @package    scss
 * @subpackage model
 * @author     David Durost
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseScssWeek extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('scss_week');
        $this->hasColumn('label', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('start_date', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('end_date', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('tte', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('camp_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ScssCamp as Camp', array(
             'local' => 'camp_id',
             'foreign' => 'id'));

        $this->hasMany('ScssPeriod', array(
             'local' => 'id',
             'foreign' => 'week_id'));

        $this->hasOne('ScssTroopRotation', array(
             'local' => 'id',
             'foreign' => 'week_id'));

        $this->hasMany('ScssTroopEnrollment', array(
             'local' => 'id',
             'foreign' => 'week_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'label',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}