<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Comment', 'doctrine');

/**
 * BaseComment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $record_model
 * @property integer $record_id
 * @property string $author_name
 * @property string $author_email
 * @property string $author_website
 * @property string $body
 * @property integer $is_delete
 * @property string $edition_reason
 * @property integer $reply
 * @property integer $user_id
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Doctrine_Collection $Comment
 * @property SfGuardUser $SfGuardUser
 * @property Doctrine_Collection $CommentReport
 * 
 * @method integer             getId()             Returns the current record's "id" value
 * @method string              getRecordModel()    Returns the current record's "record_model" value
 * @method integer             getRecordId()       Returns the current record's "record_id" value
 * @method string              getAuthorName()     Returns the current record's "author_name" value
 * @method string              getAuthorEmail()    Returns the current record's "author_email" value
 * @method string              getAuthorWebsite()  Returns the current record's "author_website" value
 * @method string              getBody()           Returns the current record's "body" value
 * @method integer             getIsDelete()       Returns the current record's "is_delete" value
 * @method string              getEditionReason()  Returns the current record's "edition_reason" value
 * @method integer             getReply()          Returns the current record's "reply" value
 * @method integer             getUserId()         Returns the current record's "user_id" value
 * @method timestamp           getCreatedAt()      Returns the current record's "created_at" value
 * @method timestamp           getUpdatedAt()      Returns the current record's "updated_at" value
 * @method Doctrine_Collection getComment()        Returns the current record's "Comment" collection
 * @method SfGuardUser         getSfGuardUser()    Returns the current record's "SfGuardUser" value
 * @method Doctrine_Collection getCommentReport()  Returns the current record's "CommentReport" collection
 * @method Comment             setId()             Sets the current record's "id" value
 * @method Comment             setRecordModel()    Sets the current record's "record_model" value
 * @method Comment             setRecordId()       Sets the current record's "record_id" value
 * @method Comment             setAuthorName()     Sets the current record's "author_name" value
 * @method Comment             setAuthorEmail()    Sets the current record's "author_email" value
 * @method Comment             setAuthorWebsite()  Sets the current record's "author_website" value
 * @method Comment             setBody()           Sets the current record's "body" value
 * @method Comment             setIsDelete()       Sets the current record's "is_delete" value
 * @method Comment             setEditionReason()  Sets the current record's "edition_reason" value
 * @method Comment             setReply()          Sets the current record's "reply" value
 * @method Comment             setUserId()         Sets the current record's "user_id" value
 * @method Comment             setCreatedAt()      Sets the current record's "created_at" value
 * @method Comment             setUpdatedAt()      Sets the current record's "updated_at" value
 * @method Comment             setComment()        Sets the current record's "Comment" collection
 * @method Comment             setSfGuardUser()    Sets the current record's "SfGuardUser" value
 * @method Comment             setCommentReport()  Sets the current record's "CommentReport" collection
 * 
 * @package    scss
 * @subpackage model
 * @author     David Durost
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseComment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('comment');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('record_model', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('record_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('author_name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('author_email', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('author_website', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('body', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('is_delete', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('edition_reason', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('reply', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('user_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Comment', array(
             'local' => 'id',
             'foreign' => 'reply'));

        $this->hasOne('SfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasMany('CommentReport', array(
             'local' => 'id',
             'foreign' => 'id_comment'));
    }
}