<?php

/**
 * BaseScssStaff
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $first_name
 * @property string $last_name
 * @property timestamp $dob
 * @property integer $cabin_id
 * @property ScssCabin $Cabin
 * @property Doctrine_Collection $ScssArea
 * @property Doctrine_Collection $ScssClass
 * 
 * @method string              getFirstName()  Returns the current record's "first_name" value
 * @method string              getLastName()   Returns the current record's "last_name" value
 * @method timestamp           getDob()        Returns the current record's "dob" value
 * @method integer             getCabinId()    Returns the current record's "cabin_id" value
 * @method ScssCabin           getCabin()      Returns the current record's "Cabin" value
 * @method Doctrine_Collection getScssArea()   Returns the current record's "ScssArea" collection
 * @method Doctrine_Collection getScssClass()  Returns the current record's "ScssClass" collection
 * @method ScssStaff           setFirstName()  Sets the current record's "first_name" value
 * @method ScssStaff           setLastName()   Sets the current record's "last_name" value
 * @method ScssStaff           setDob()        Sets the current record's "dob" value
 * @method ScssStaff           setCabinId()    Sets the current record's "cabin_id" value
 * @method ScssStaff           setCabin()      Sets the current record's "Cabin" value
 * @method ScssStaff           setScssArea()   Sets the current record's "ScssArea" collection
 * @method ScssStaff           setScssClass()  Sets the current record's "ScssClass" collection
 * 
 * @package    scss
 * @subpackage model
 * @author     David Durost
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseScssStaff extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('scss_staff');
        $this->hasColumn('first_name', 'string', 60, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 60,
             ));
        $this->hasColumn('last_name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('dob', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('cabin_id', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ScssCabin as Cabin', array(
             'local' => 'cabin_id',
             'foreign' => 'id'));

        $this->hasMany('ScssArea', array(
             'local' => 'id',
             'foreign' => 'staff_id'));

        $this->hasMany('ScssClass', array(
             'local' => 'id',
             'foreign' => 'staff_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'first_name',
              1 => 'last_name',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}