<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DdPortfolioSkill', 'doctrine');

/**
 * BaseDdPortfolioSkill
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $dd_portfolio_id
 * @property integer $dd_skill_id
 * @property DdPortfolio $DdPortfolio
 * @property DdSkill $DdSkill
 * 
 * @method integer          getId()              Returns the current record's "id" value
 * @method integer          getDdPortfolioId()   Returns the current record's "dd_portfolio_id" value
 * @method integer          getDdSkillId()       Returns the current record's "dd_skill_id" value
 * @method DdPortfolio      getDdPortfolio()     Returns the current record's "DdPortfolio" value
 * @method DdSkill          getDdSkill()         Returns the current record's "DdSkill" value
 * @method DdPortfolioSkill setId()              Sets the current record's "id" value
 * @method DdPortfolioSkill setDdPortfolioId()   Sets the current record's "dd_portfolio_id" value
 * @method DdPortfolioSkill setDdSkillId()       Sets the current record's "dd_skill_id" value
 * @method DdPortfolioSkill setDdPortfolio()     Sets the current record's "DdPortfolio" value
 * @method DdPortfolioSkill setDdSkill()         Sets the current record's "DdSkill" value
 * 
 * @package    scss
 * @subpackage model
 * @author     David Durost
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDdPortfolioSkill extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dd_portfolio_skill');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('dd_portfolio_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('dd_skill_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('DdPortfolio', array(
             'local' => 'dd_portfolio_id',
             'foreign' => 'id'));

        $this->hasOne('DdSkill', array(
             'local' => 'dd_skill_id',
             'foreign' => 'id'));
    }
}