<?php

/**
 * BaseScssZone
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $country_id
 * @property string $code
 * @property string $name
 * @property ScssCountry $Country
 * @property Doctrine_Collection $ScssDistrict
 * @property Doctrine_Collection $ScssAddressBook
 * 
 * @method integer             getCountryId()       Returns the current record's "country_id" value
 * @method string              getCode()            Returns the current record's "code" value
 * @method string              getName()            Returns the current record's "name" value
 * @method ScssCountry         getCountry()         Returns the current record's "Country" value
 * @method Doctrine_Collection getScssDistrict()    Returns the current record's "ScssDistrict" collection
 * @method Doctrine_Collection getScssAddressBook() Returns the current record's "ScssAddressBook" collection
 * @method ScssZone            setCountryId()       Sets the current record's "country_id" value
 * @method ScssZone            setCode()            Sets the current record's "code" value
 * @method ScssZone            setName()            Sets the current record's "name" value
 * @method ScssZone            setCountry()         Sets the current record's "Country" value
 * @method ScssZone            setScssDistrict()    Sets the current record's "ScssDistrict" collection
 * @method ScssZone            setScssAddressBook() Sets the current record's "ScssAddressBook" collection
 * 
 * @package    scss
 * @subpackage model
 * @author     David Durost
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseScssZone extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('scss_zone');
        $this->hasColumn('country_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('code', 'string', 32, array(
             'type' => 'string',
             'length' => 32,
             ));
        $this->hasColumn('name', 'string', 64, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 64,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ScssCountry as Country', array(
             'local' => 'country_id',
             'foreign' => 'id'));

        $this->hasMany('ScssDistrict', array(
             'local' => 'id',
             'foreign' => 'zone_id'));

        $this->hasMany('ScssAddressBook', array(
             'local' => 'id',
             'foreign' => 'zone_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}