<?php

/**
 * BaseScssAddressBook
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $label
 * @property string $street
 * @property string $suburb
 * @property string $city
 * @property integer $zone_id
 * @property string $postal_code
 * @property ScssZone $Zone
 * @property Doctrine_Collection $ScssCamp
 * 
 * @method string              getLabel()       Returns the current record's "label" value
 * @method string              getStreet()      Returns the current record's "street" value
 * @method string              getSuburb()      Returns the current record's "suburb" value
 * @method string              getCity()        Returns the current record's "city" value
 * @method integer             getZoneId()      Returns the current record's "zone_id" value
 * @method string              getPostalCode()  Returns the current record's "postal_code" value
 * @method ScssZone            getZone()        Returns the current record's "Zone" value
 * @method Doctrine_Collection getScssCamp()    Returns the current record's "ScssCamp" collection
 * @method ScssAddressBook     setLabel()       Sets the current record's "label" value
 * @method ScssAddressBook     setStreet()      Sets the current record's "street" value
 * @method ScssAddressBook     setSuburb()      Sets the current record's "suburb" value
 * @method ScssAddressBook     setCity()        Sets the current record's "city" value
 * @method ScssAddressBook     setZoneId()      Sets the current record's "zone_id" value
 * @method ScssAddressBook     setPostalCode()  Sets the current record's "postal_code" value
 * @method ScssAddressBook     setZone()        Sets the current record's "Zone" value
 * @method ScssAddressBook     setScssCamp()    Sets the current record's "ScssCamp" collection
 * 
 * @package    scss
 * @subpackage model
 * @author     David Durost
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseScssAddressBook extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('scss_address_book');
        $this->hasColumn('label', 'string', 30, array(
             'type' => 'string',
             'length' => 30,
             ));
        $this->hasColumn('street', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('suburb', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('city', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 30,
             ));
        $this->hasColumn('zone_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('postal_code', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 10,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ScssZone as Zone', array(
             'local' => 'zone_id',
             'foreign' => 'id'));

        $this->hasMany('ScssCamp', array(
             'local' => 'id',
             'foreign' => 'address_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}