<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CategoryObject', 'doctrine');

/**
 * BaseCategoryObject
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $category_id
 * @property string $categorized_model
 * @property integer $categorized_id
 * 
 * @method integer        getCategoryId()        Returns the current record's "category_id" value
 * @method string         getCategorizedModel()  Returns the current record's "categorized_model" value
 * @method integer        getCategorizedId()     Returns the current record's "categorized_id" value
 * @method CategoryObject setCategoryId()        Sets the current record's "category_id" value
 * @method CategoryObject setCategorizedModel()  Sets the current record's "categorized_model" value
 * @method CategoryObject setCategorizedId()     Sets the current record's "categorized_id" value
 * 
 * @package    scss
 * @subpackage model
 * @author     David Durost
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategoryObject extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('category_object');
        $this->hasColumn('category_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('categorized_model', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('categorized_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}