<?php

/**
 * BaseScssDistrict
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $code
 * @property string $img
 * @property integer $zone_id
 * @property ScssZone $Zone
 * @property Doctrine_Collection $ScssCamp
 * @property Doctrine_Collection $ScssTroop
 * 
 * @method string              getName()      Returns the current record's "name" value
 * @method string              getCode()      Returns the current record's "code" value
 * @method string              getImg()       Returns the current record's "img" value
 * @method integer             getZoneId()    Returns the current record's "zone_id" value
 * @method ScssZone            getZone()      Returns the current record's "Zone" value
 * @method Doctrine_Collection getScssCamp()  Returns the current record's "ScssCamp" collection
 * @method Doctrine_Collection getScssTroop() Returns the current record's "ScssTroop" collection
 * @method ScssDistrict        setName()      Sets the current record's "name" value
 * @method ScssDistrict        setCode()      Sets the current record's "code" value
 * @method ScssDistrict        setImg()       Sets the current record's "img" value
 * @method ScssDistrict        setZoneId()    Sets the current record's "zone_id" value
 * @method ScssDistrict        setZone()      Sets the current record's "Zone" value
 * @method ScssDistrict        setScssCamp()  Sets the current record's "ScssCamp" collection
 * @method ScssDistrict        setScssTroop() Sets the current record's "ScssTroop" collection
 * 
 * @package    scss
 * @subpackage model
 * @author     David Durost
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseScssDistrict extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('scss_district');
        $this->hasColumn('name', 'string', 60, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 60,
             ));
        $this->hasColumn('code', 'string', 2, array(
             'type' => 'string',
             'length' => 2,
             ));
        $this->hasColumn('img', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
        $this->hasColumn('zone_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ScssZone as Zone', array(
             'local' => 'zone_id',
             'foreign' => 'id'));

        $this->hasMany('ScssCamp', array(
             'local' => 'id',
             'foreign' => 'district_id'));

        $this->hasMany('ScssTroop', array(
             'local' => 'id',
             'foreign' => 'district_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}