<?php

/**
 * BaseScssCountry
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $iso_code2
 * @property string $iso_code3
 * @property integer $address_format_id
 * @property ScssAddressFormat $AddressFormat
 * @property Doctrine_Collection $ScssZone
 * 
 * @method string              getName()              Returns the current record's "name" value
 * @method string              getIsoCode2()          Returns the current record's "iso_code2" value
 * @method string              getIsoCode3()          Returns the current record's "iso_code3" value
 * @method integer             getAddressFormatId()   Returns the current record's "address_format_id" value
 * @method ScssAddressFormat   getAddressFormat()     Returns the current record's "AddressFormat" value
 * @method Doctrine_Collection getScssZone()          Returns the current record's "ScssZone" collection
 * @method ScssCountry         setName()              Sets the current record's "name" value
 * @method ScssCountry         setIsoCode2()          Sets the current record's "iso_code2" value
 * @method ScssCountry         setIsoCode3()          Sets the current record's "iso_code3" value
 * @method ScssCountry         setAddressFormatId()   Sets the current record's "address_format_id" value
 * @method ScssCountry         setAddressFormat()     Sets the current record's "AddressFormat" value
 * @method ScssCountry         setScssZone()          Sets the current record's "ScssZone" collection
 * 
 * @package    scss
 * @subpackage model
 * @author     David Durost
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseScssCountry extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('scss_country');
        $this->hasColumn('name', 'string', 64, array(
             'unique' => true,
             'type' => 'string',
             'notnull' => true,
             'length' => 64,
             ));
        $this->hasColumn('iso_code2', 'string', 2, array(
             'unique' => true,
             'type' => 'string',
             'length' => 2,
             ));
        $this->hasColumn('iso_code3', 'string', 3, array(
             'unique' => true,
             'type' => 'string',
             'length' => 3,
             ));
        $this->hasColumn('address_format_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ScssAddressFormat as AddressFormat', array(
             'local' => 'address_format_id',
             'foreign' => 'id'));

        $this->hasMany('ScssZone', array(
             'local' => 'id',
             'foreign' => 'country_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}