<?php

/**
 * BaseScssTroop
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $number
 * @property string $img
 * @property integer $district_id
 * @property ScssDistrict $District
 * @property Doctrine_Collection $ScssPatrol
 * @property Doctrine_Collection $ScssTroopEnrollment
 * @property Doctrine_Collection $sfGuardUserProfile
 * 
 * @method string              getNumber()              Returns the current record's "number" value
 * @method string              getImg()                 Returns the current record's "img" value
 * @method integer             getDistrictId()          Returns the current record's "district_id" value
 * @method ScssDistrict        getDistrict()            Returns the current record's "District" value
 * @method Doctrine_Collection getScssPatrol()          Returns the current record's "ScssPatrol" collection
 * @method Doctrine_Collection getScssTroopEnrollment() Returns the current record's "ScssTroopEnrollment" collection
 * @method Doctrine_Collection getSfGuardUserProfile()  Returns the current record's "sfGuardUserProfile" collection
 * @method ScssTroop           setNumber()              Sets the current record's "number" value
 * @method ScssTroop           setImg()                 Sets the current record's "img" value
 * @method ScssTroop           setDistrictId()          Sets the current record's "district_id" value
 * @method ScssTroop           setDistrict()            Sets the current record's "District" value
 * @method ScssTroop           setScssPatrol()          Sets the current record's "ScssPatrol" collection
 * @method ScssTroop           setScssTroopEnrollment() Sets the current record's "ScssTroopEnrollment" collection
 * @method ScssTroop           setSfGuardUserProfile()  Sets the current record's "sfGuardUserProfile" collection
 * 
 * @package    scss
 * @subpackage model
 * @author     David Durost
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseScssTroop extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('scss_troop');
        $this->hasColumn('number', 'string', 5, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 5,
             ));
        $this->hasColumn('img', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
        $this->hasColumn('district_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ScssDistrict as District', array(
             'local' => 'district_id',
             'foreign' => 'id'));

        $this->hasMany('ScssPatrol', array(
             'local' => 'id',
             'foreign' => 'troop_id'));

        $this->hasMany('ScssTroopEnrollment', array(
             'local' => 'id',
             'foreign' => 'troop_id'));

        $this->hasMany('sfGuardUserProfile', array(
             'local' => 'id',
             'foreign' => 'troop_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'number',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}