<?php

/**
 * BaseScssAddressFormat
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $address_format
 * @property string $address_summary
 * @property Doctrine_Collection $ScssCountry
 * 
 * @method string              getAddressFormat()   Returns the current record's "address_format" value
 * @method string              getAddressSummary()  Returns the current record's "address_summary" value
 * @method Doctrine_Collection getScssCountry()     Returns the current record's "ScssCountry" collection
 * @method ScssAddressFormat   setAddressFormat()   Sets the current record's "address_format" value
 * @method ScssAddressFormat   setAddressSummary()  Sets the current record's "address_summary" value
 * @method ScssAddressFormat   setScssCountry()     Sets the current record's "ScssCountry" collection
 * 
 * @package    scss
 * @subpackage model
 * @author     David Durost
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseScssAddressFormat extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('scss_address_format');
        $this->hasColumn('address_format', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('address_summary', 'string', 48, array(
             'type' => 'string',
             'length' => 48,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ScssCountry', array(
             'local' => 'id',
             'foreign' => 'address_format_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}