<?php

/**
 * BaseScssPatrol
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $img
 * @property string $color
 * @property integer $troop_id
 * @property ScssTroop $Troop
 * @property Doctrine_Collection $ScssScout
 * 
 * @method string              getName()      Returns the current record's "name" value
 * @method string              getImg()       Returns the current record's "img" value
 * @method string              getColor()     Returns the current record's "color" value
 * @method integer             getTroopId()   Returns the current record's "troop_id" value
 * @method ScssTroop           getTroop()     Returns the current record's "Troop" value
 * @method Doctrine_Collection getScssScout() Returns the current record's "ScssScout" collection
 * @method ScssPatrol          setName()      Sets the current record's "name" value
 * @method ScssPatrol          setImg()       Sets the current record's "img" value
 * @method ScssPatrol          setColor()     Sets the current record's "color" value
 * @method ScssPatrol          setTroopId()   Sets the current record's "troop_id" value
 * @method ScssPatrol          setTroop()     Sets the current record's "Troop" value
 * @method ScssPatrol          setScssScout() Sets the current record's "ScssScout" collection
 * 
 * @package    scss
 * @subpackage model
 * @author     David Durost
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseScssPatrol extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('scss_patrol');
        $this->hasColumn('name', 'string', 60, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 60,
             ));
        $this->hasColumn('img', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
        $this->hasColumn('color', 'string', 6, array(
             'type' => 'string',
             'length' => 6,
             ));
        $this->hasColumn('troop_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ScssTroop as Troop', array(
             'local' => 'troop_id',
             'foreign' => 'id'));

        $this->hasMany('ScssScout', array(
             'local' => 'id',
             'foreign' => 'patrol_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}