<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('DdSkill', 'doctrine');

/**
 * BaseDdSkill
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $image
 * @property string $url
 * @property string $description
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property string $slug
 * @property Doctrine_Collection $DdPortfolioSkill
 * 
 * @method integer             getId()               Returns the current record's "id" value
 * @method string              getName()             Returns the current record's "name" value
 * @method string              getImage()            Returns the current record's "image" value
 * @method string              getUrl()              Returns the current record's "url" value
 * @method string              getDescription()      Returns the current record's "description" value
 * @method timestamp           getCreatedAt()        Returns the current record's "created_at" value
 * @method timestamp           getUpdatedAt()        Returns the current record's "updated_at" value
 * @method string              getSlug()             Returns the current record's "slug" value
 * @method Doctrine_Collection getDdPortfolioSkill() Returns the current record's "DdPortfolioSkill" collection
 * @method DdSkill             setId()               Sets the current record's "id" value
 * @method DdSkill             setName()             Sets the current record's "name" value
 * @method DdSkill             setImage()            Sets the current record's "image" value
 * @method DdSkill             setUrl()              Sets the current record's "url" value
 * @method DdSkill             setDescription()      Sets the current record's "description" value
 * @method DdSkill             setCreatedAt()        Sets the current record's "created_at" value
 * @method DdSkill             setUpdatedAt()        Sets the current record's "updated_at" value
 * @method DdSkill             setSlug()             Sets the current record's "slug" value
 * @method DdSkill             setDdPortfolioSkill() Sets the current record's "DdPortfolioSkill" collection
 * 
 * @package    scss
 * @subpackage model
 * @author     David Durost
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDdSkill extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dd_skill');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('image', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('url', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('slug', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('DdPortfolioSkill', array(
             'local' => 'id',
             'foreign' => 'dd_skill_id'));
    }
}