<?php

/**
 * BaseScssScoutEnrollment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $scout_id
 * @property integer $class_id
 * @property ScssScout $Scout
 * @property ScssClass $Class
 * 
 * @method integer             getScoutId()  Returns the current record's "scout_id" value
 * @method integer             getClassId()  Returns the current record's "class_id" value
 * @method ScssScout           getScout()    Returns the current record's "Scout" value
 * @method ScssClass           getClass()    Returns the current record's "Class" value
 * @method ScssScoutEnrollment setScoutId()  Sets the current record's "scout_id" value
 * @method ScssScoutEnrollment setClassId()  Sets the current record's "class_id" value
 * @method ScssScoutEnrollment setScout()    Sets the current record's "Scout" value
 * @method ScssScoutEnrollment setClass()    Sets the current record's "Class" value
 * 
 * @package    scss
 * @subpackage model
 * @author     David Durost
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseScssScoutEnrollment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('scss_scout_enrollment');
        $this->hasColumn('scout_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('class_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ScssScout as Scout', array(
             'local' => 'scout_id',
             'foreign' => 'id'));

        $this->hasOne('ScssClass as Class', array(
             'local' => 'class_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}