<?php

/**
 * BaseScssTroopRotation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $description
 * @property integer $week_id
 * @property ScssWeek $Week
 * @property Doctrine_Collection $ScssTroopEnrollment
 * 
 * @method string              getName()                Returns the current record's "name" value
 * @method string              getDescription()         Returns the current record's "description" value
 * @method integer             getWeekId()              Returns the current record's "week_id" value
 * @method ScssWeek            getWeek()                Returns the current record's "Week" value
 * @method Doctrine_Collection getScssTroopEnrollment() Returns the current record's "ScssTroopEnrollment" collection
 * @method ScssTroopRotation   setName()                Sets the current record's "name" value
 * @method ScssTroopRotation   setDescription()         Sets the current record's "description" value
 * @method ScssTroopRotation   setWeekId()              Sets the current record's "week_id" value
 * @method ScssTroopRotation   setWeek()                Sets the current record's "Week" value
 * @method ScssTroopRotation   setScssTroopEnrollment() Sets the current record's "ScssTroopEnrollment" collection
 * 
 * @package    scss
 * @subpackage model
 * @author     David Durost
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseScssTroopRotation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('scss_troop_rotation');
        $this->hasColumn('name', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('week_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ScssWeek as Week', array(
             'local' => 'week_id',
             'foreign' => 'id'));

        $this->hasMany('ScssTroopEnrollment', array(
             'local' => 'id',
             'foreign' => 'rotation_id'));
    }
}