<?php

/**
 * BaseScssCamp
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $address_id
 * @property integer $district_id
 * @property string $phone
 * @property string $fax
 * @property string $email
 * @property string $url
 * @property ScssAddressBook $Address
 * @property ScssDistrict $District
 * @property Doctrine_Collection $ScssArea
 * @property Doctrine_Collection $ScssCampsite
 * @property Doctrine_Collection $ScssCabin
 * @property Doctrine_Collection $ScssWeek
 * @property Doctrine_Collection $ScssCourse
 * 
 * @method string              getName()         Returns the current record's "name" value
 * @method integer             getAddressId()    Returns the current record's "address_id" value
 * @method integer             getDistrictId()   Returns the current record's "district_id" value
 * @method string              getPhone()        Returns the current record's "phone" value
 * @method string              getFax()          Returns the current record's "fax" value
 * @method string              getEmail()        Returns the current record's "email" value
 * @method string              getUrl()          Returns the current record's "url" value
 * @method ScssAddressBook     getAddress()      Returns the current record's "Address" value
 * @method ScssDistrict        getDistrict()     Returns the current record's "District" value
 * @method Doctrine_Collection getScssArea()     Returns the current record's "ScssArea" collection
 * @method Doctrine_Collection getScssCampsite() Returns the current record's "ScssCampsite" collection
 * @method Doctrine_Collection getScssCabin()    Returns the current record's "ScssCabin" collection
 * @method Doctrine_Collection getScssWeek()     Returns the current record's "ScssWeek" collection
 * @method Doctrine_Collection getScssCourse()   Returns the current record's "ScssCourse" collection
 * @method ScssCamp            setName()         Sets the current record's "name" value
 * @method ScssCamp            setAddressId()    Sets the current record's "address_id" value
 * @method ScssCamp            setDistrictId()   Sets the current record's "district_id" value
 * @method ScssCamp            setPhone()        Sets the current record's "phone" value
 * @method ScssCamp            setFax()          Sets the current record's "fax" value
 * @method ScssCamp            setEmail()        Sets the current record's "email" value
 * @method ScssCamp            setUrl()          Sets the current record's "url" value
 * @method ScssCamp            setAddress()      Sets the current record's "Address" value
 * @method ScssCamp            setDistrict()     Sets the current record's "District" value
 * @method ScssCamp            setScssArea()     Sets the current record's "ScssArea" collection
 * @method ScssCamp            setScssCampsite() Sets the current record's "ScssCampsite" collection
 * @method ScssCamp            setScssCabin()    Sets the current record's "ScssCabin" collection
 * @method ScssCamp            setScssWeek()     Sets the current record's "ScssWeek" collection
 * @method ScssCamp            setScssCourse()   Sets the current record's "ScssCourse" collection
 * 
 * @package    scss
 * @subpackage model
 * @author     David Durost
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseScssCamp extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('scss_camp');
        $this->hasColumn('name', 'string', 150, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 150,
             ));
        $this->hasColumn('address_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('district_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('phone', 'string', 40, array(
             'type' => 'string',
             'length' => 40,
             ));
        $this->hasColumn('fax', 'string', 40, array(
             'type' => 'string',
             'length' => 40,
             ));
        $this->hasColumn('email', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
        $this->hasColumn('url', 'string', 200, array(
             'type' => 'string',
             'extra' => 'link',
             'length' => 200,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ScssAddressBook as Address', array(
             'local' => 'address_id',
             'foreign' => 'id'));

        $this->hasOne('ScssDistrict as District', array(
             'local' => 'district_id',
             'foreign' => 'id'));

        $this->hasMany('ScssArea', array(
             'local' => 'id',
             'foreign' => 'camp_id'));

        $this->hasMany('ScssCampsite', array(
             'local' => 'id',
             'foreign' => 'camp_id'));

        $this->hasMany('ScssCabin', array(
             'local' => 'id',
             'foreign' => 'camp_id'));

        $this->hasMany('ScssWeek', array(
             'local' => 'id',
             'foreign' => 'camp_id'));

        $this->hasMany('ScssCourse', array(
             'local' => 'id',
             'foreign' => 'camp_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}