<?php

/**
 * BasesfGuardUserProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $access_level
 * @property integer $troop_id
 * @property string $avatar
 * @property varchar $first_name
 * @property varchar $last_name
 * @property integer $facebook_uid
 * @property varchar $email
 * @property varchar $email_hash
 * @property integer $active_troop_id
 * @property sfGuardUser $User
 * @property ScssTroop $Troop
 * @property ScssTroop $ActiveTroop
 * 
 * @method integer            getUserId()          Returns the current record's "user_id" value
 * @method integer            getAccessLevel()     Returns the current record's "access_level" value
 * @method integer            getTroopId()         Returns the current record's "troop_id" value
 * @method string             getAvatar()          Returns the current record's "avatar" value
 * @method varchar            getFirstName()       Returns the current record's "first_name" value
 * @method varchar            getLastName()        Returns the current record's "last_name" value
 * @method integer            getFacebookUid()     Returns the current record's "facebook_uid" value
 * @method varchar            getEmail()           Returns the current record's "email" value
 * @method varchar            getEmailHash()       Returns the current record's "email_hash" value
 * @method integer            getActiveTroopId()   Returns the current record's "active_troop_id" value
 * @method sfGuardUser        getUser()            Returns the current record's "User" value
 * @method ScssTroop          getTroop()           Returns the current record's "Troop" value
 * @method ScssTroop          getActiveTroop()     Returns the current record's "ActiveTroop" value
 * @method sfGuardUserProfile setUserId()          Sets the current record's "user_id" value
 * @method sfGuardUserProfile setAccessLevel()     Sets the current record's "access_level" value
 * @method sfGuardUserProfile setTroopId()         Sets the current record's "troop_id" value
 * @method sfGuardUserProfile setAvatar()          Sets the current record's "avatar" value
 * @method sfGuardUserProfile setFirstName()       Sets the current record's "first_name" value
 * @method sfGuardUserProfile setLastName()        Sets the current record's "last_name" value
 * @method sfGuardUserProfile setFacebookUid()     Sets the current record's "facebook_uid" value
 * @method sfGuardUserProfile setEmail()           Sets the current record's "email" value
 * @method sfGuardUserProfile setEmailHash()       Sets the current record's "email_hash" value
 * @method sfGuardUserProfile setActiveTroopId()   Sets the current record's "active_troop_id" value
 * @method sfGuardUserProfile setUser()            Sets the current record's "User" value
 * @method sfGuardUserProfile setTroop()           Sets the current record's "Troop" value
 * @method sfGuardUserProfile setActiveTroop()     Sets the current record's "ActiveTroop" value
 * 
 * @package    scss
 * @subpackage model
 * @author     David Durost
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfGuardUserProfile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_user_profile');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('access_level', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 1,
             ));
        $this->hasColumn('troop_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('avatar', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '/images/user_files/logos/avatar/default.png',
             ));
        $this->hasColumn('first_name', 'varchar', 20, array(
             'type' => 'varchar',
             'length' => 20,
             ));
        $this->hasColumn('last_name', 'varchar', 20, array(
             'type' => 'varchar',
             'length' => 20,
             ));
        $this->hasColumn('facebook_uid', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('email', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('email_hash', 'varchar', 255, array(
             'type' => 'varchar',
             'length' => 255,
             ));
        $this->hasColumn('active_troop_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasOne('ScssTroop as Troop', array(
             'local' => 'troop_id',
             'foreign' => 'id'));

        $this->hasOne('ScssTroop as ActiveTroop', array(
             'local' => 'active_troop_id',
             'foreign' => 'id'));
    }
}