<?php

/**
 * BaseScssRequirement
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $label
 * @property int $parent_id
 * @property string $text
 * @property boolean $optional
 * @property integer $mb_id
 * @property ScssMeritBadge $MeritBadge
 * 
 * @method string          getLabel()      Returns the current record's "label" value
 * @method int             getParentId()   Returns the current record's "parent_id" value
 * @method string          getText()       Returns the current record's "text" value
 * @method boolean         getOptional()   Returns the current record's "optional" value
 * @method integer         getMbId()       Returns the current record's "mb_id" value
 * @method ScssMeritBadge  getMeritBadge() Returns the current record's "MeritBadge" value
 * @method ScssRequirement setLabel()      Sets the current record's "label" value
 * @method ScssRequirement setParentId()   Sets the current record's "parent_id" value
 * @method ScssRequirement setText()       Sets the current record's "text" value
 * @method ScssRequirement setOptional()   Sets the current record's "optional" value
 * @method ScssRequirement setMbId()       Sets the current record's "mb_id" value
 * @method ScssRequirement setMeritBadge() Sets the current record's "MeritBadge" value
 * 
 * @package    scss
 * @subpackage model
 * @author     David Durost
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseScssRequirement extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('scss_requirement');
        $this->hasColumn('label', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 10,
             ));
        $this->hasColumn('parent_id', 'int', null, array(
             'type' => 'int',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('text', 'string', 500, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 500,
             ));
        $this->hasColumn('optional', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('mb_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));

        $this->setSubClasses(array(
             'ScssSubRequirement' => 
             array(
              'parent_id' => 'ScssSubRequirement',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ScssMeritBadge as MeritBadge', array(
             'local' => 'mb_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'label',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}