<?php

/**
 * BaseScssMeritBadge
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property int $num_reqs
 * @property boolean $tte
 * @property string $img
 * @property Doctrine_Collection $ScssCourse
 * @property Doctrine_Collection $ScssRequirement
 * 
 * @method string              getName()            Returns the current record's "name" value
 * @method int                 getNumReqs()         Returns the current record's "num_reqs" value
 * @method boolean             getTte()             Returns the current record's "tte" value
 * @method string              getImg()             Returns the current record's "img" value
 * @method Doctrine_Collection getScssCourse()      Returns the current record's "ScssCourse" collection
 * @method Doctrine_Collection getScssRequirement() Returns the current record's "ScssRequirement" collection
 * @method ScssMeritBadge      setName()            Sets the current record's "name" value
 * @method ScssMeritBadge      setNumReqs()         Sets the current record's "num_reqs" value
 * @method ScssMeritBadge      setTte()             Sets the current record's "tte" value
 * @method ScssMeritBadge      setImg()             Sets the current record's "img" value
 * @method ScssMeritBadge      setScssCourse()      Sets the current record's "ScssCourse" collection
 * @method ScssMeritBadge      setScssRequirement() Sets the current record's "ScssRequirement" collection
 * 
 * @package    scss
 * @subpackage model
 * @author     David Durost
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseScssMeritBadge extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('scss_merit_badge');
        $this->hasColumn('name', 'string', 150, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 150,
             ));
        $this->hasColumn('num_reqs', 'int', null, array(
             'type' => 'int',
             ));
        $this->hasColumn('tte', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('img', 'string', null, array(
             'type' => 'string',
             'default' => 'tba.gif',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ScssCourse', array(
             'local' => 'id',
             'foreign' => 'meritbadge_id'));

        $this->hasMany('ScssRequirement', array(
             'local' => 'id',
             'foreign' => 'mb_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}