<?php

/**
 * BaseScssActiveEnrollment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $troop_enrollment_id
 * @property ScssTroopEnrollment $troop_enrollment_id
 * 
 * @method ScssTroopEnrollment  getTroopEnrollmentId()   Returns the current record's "troop_enrollment_id" value
 * @method ScssActiveEnrollment setTroopEnrollmentId()   Sets the current record's "troop_enrollment_id" value
 * 
 * @package    scss
 * @subpackage model
 * @author     David Durost
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseScssActiveEnrollment extends sfGuardUserProfile
{
    public function setTableDefinition()
    {
        parent::setTableDefinition();
        $this->setTableName('scss_active_enrollment');
        $this->hasColumn('troop_enrollment_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ScssTroopEnrollment as troop_enrollment_id', array(
             'local' => 'troop_enrollment_id',
             'foreign' => 'id'));
    }
}