<?php

/**
 * BaseScssScout
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $first_name
 * @property string $last_name
 * @property timestamp $dob
 * @property integer $patrol_id
 * @property integer $rank_id
 * @property ScssPatrol $Patrol
 * @property ScssRank $Rank
 * @property Doctrine_Collection $ScssScoutEnrollment
 * 
 * @method string              getFirstName()           Returns the current record's "first_name" value
 * @method string              getLastName()            Returns the current record's "last_name" value
 * @method timestamp           getDob()                 Returns the current record's "dob" value
 * @method integer             getPatrolId()            Returns the current record's "patrol_id" value
 * @method integer             getRankId()              Returns the current record's "rank_id" value
 * @method ScssPatrol          getPatrol()              Returns the current record's "Patrol" value
 * @method ScssRank            getRank()                Returns the current record's "Rank" value
 * @method Doctrine_Collection getScssScoutEnrollment() Returns the current record's "ScssScoutEnrollment" collection
 * @method ScssScout           setFirstName()           Sets the current record's "first_name" value
 * @method ScssScout           setLastName()            Sets the current record's "last_name" value
 * @method ScssScout           setDob()                 Sets the current record's "dob" value
 * @method ScssScout           setPatrolId()            Sets the current record's "patrol_id" value
 * @method ScssScout           setRankId()              Sets the current record's "rank_id" value
 * @method ScssScout           setPatrol()              Sets the current record's "Patrol" value
 * @method ScssScout           setRank()                Sets the current record's "Rank" value
 * @method ScssScout           setScssScoutEnrollment() Sets the current record's "ScssScoutEnrollment" collection
 * 
 * @package    scss
 * @subpackage model
 * @author     David Durost
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseScssScout extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('scss_scout');
        $this->hasColumn('first_name', 'string', 60, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 60,
             ));
        $this->hasColumn('last_name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('dob', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('patrol_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('rank_id', 'integer', null, array(
             'type' => 'integer',
             'default' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ScssPatrol as Patrol', array(
             'local' => 'patrol_id',
             'foreign' => 'id'));

        $this->hasOne('ScssRank as Rank', array(
             'local' => 'rank_id',
             'foreign' => 'id'));

        $this->hasMany('ScssScoutEnrollment', array(
             'local' => 'id',
             'foreign' => 'scout_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'first_name',
              1 => 'last_name',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}