<?php

/**
 * BaseScssClass
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $course_id
 * @property integer $area_id
 * @property integer $period_id
 * @property integer $staff_id
 * @property ScssCourse $Course
 * @property ScssArea $Area
 * @property ScssPeriod $Period
 * @property ScssStaff $Staff
 * @property Doctrine_Collection $ScssScoutEnrollment
 * 
 * @method integer             getCourseId()            Returns the current record's "course_id" value
 * @method integer             getAreaId()              Returns the current record's "area_id" value
 * @method integer             getPeriodId()            Returns the current record's "period_id" value
 * @method integer             getStaffId()             Returns the current record's "staff_id" value
 * @method ScssCourse          getCourse()              Returns the current record's "Course" value
 * @method ScssArea            getArea()                Returns the current record's "Area" value
 * @method ScssPeriod          getPeriod()              Returns the current record's "Period" value
 * @method ScssStaff           getStaff()               Returns the current record's "Staff" value
 * @method Doctrine_Collection getScssScoutEnrollment() Returns the current record's "ScssScoutEnrollment" collection
 * @method ScssClass           setCourseId()            Sets the current record's "course_id" value
 * @method ScssClass           setAreaId()              Sets the current record's "area_id" value
 * @method ScssClass           setPeriodId()            Sets the current record's "period_id" value
 * @method ScssClass           setStaffId()             Sets the current record's "staff_id" value
 * @method ScssClass           setCourse()              Sets the current record's "Course" value
 * @method ScssClass           setArea()                Sets the current record's "Area" value
 * @method ScssClass           setPeriod()              Sets the current record's "Period" value
 * @method ScssClass           setStaff()               Sets the current record's "Staff" value
 * @method ScssClass           setScssScoutEnrollment() Sets the current record's "ScssScoutEnrollment" collection
 * 
 * @package    scss
 * @subpackage model
 * @author     David Durost
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseScssClass extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('scss_class');
        $this->hasColumn('course_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('area_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('period_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('staff_id', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ScssCourse as Course', array(
             'local' => 'course_id',
             'foreign' => 'id'));

        $this->hasOne('ScssArea as Area', array(
             'local' => 'area_id',
             'foreign' => 'id'));

        $this->hasOne('ScssPeriod as Period', array(
             'local' => 'period_id',
             'foreign' => 'id'));

        $this->hasOne('ScssStaff as Staff', array(
             'local' => 'staff_id',
             'foreign' => 'id'));

        $this->hasMany('ScssScoutEnrollment', array(
             'local' => 'id',
             'foreign' => 'class_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}