<?php

/**
 * BaseScssSubArea
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * 
 * @package    scss
 * @subpackage model
 * @author     David Durost
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseScssSubArea extends ScssArea
{
    public function setUp()
    {
        parent::setUp();
        
    }
}