<?php

/**
 * BaseScssArea
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $parent_id
 * @property integer $camp_id
 * @property integer $staff_id
 * @property ScssCamp $Camp
 * @property ScssStaff $Staff
 * @property Doctrine_Collection $ScssClass
 * 
 * @method string              getName()      Returns the current record's "name" value
 * @method integer             getParentId()  Returns the current record's "parent_id" value
 * @method integer             getCampId()    Returns the current record's "camp_id" value
 * @method integer             getStaffId()   Returns the current record's "staff_id" value
 * @method ScssCamp            getCamp()      Returns the current record's "Camp" value
 * @method ScssStaff           getStaff()     Returns the current record's "Staff" value
 * @method Doctrine_Collection getScssClass() Returns the current record's "ScssClass" collection
 * @method ScssArea            setName()      Sets the current record's "name" value
 * @method ScssArea            setParentId()  Sets the current record's "parent_id" value
 * @method ScssArea            setCampId()    Sets the current record's "camp_id" value
 * @method ScssArea            setStaffId()   Sets the current record's "staff_id" value
 * @method ScssArea            setCamp()      Sets the current record's "Camp" value
 * @method ScssArea            setStaff()     Sets the current record's "Staff" value
 * @method ScssArea            setScssClass() Sets the current record's "ScssClass" collection
 * 
 * @package    scss
 * @subpackage model
 * @author     David Durost
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseScssArea extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('scss_area');
        $this->hasColumn('name', 'string', 150, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 150,
             ));
        $this->hasColumn('parent_id', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
        $this->hasColumn('camp_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('staff_id', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->setSubClasses(array(
             'ScssSubArea' => 
             array(
              'parent_id' => 'ScssSubArea',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ScssCamp as Camp', array(
             'local' => 'camp_id',
             'foreign' => 'id'));

        $this->hasOne('ScssStaff as Staff', array(
             'local' => 'staff_id',
             'foreign' => 'id'));

        $this->hasMany('ScssClass', array(
             'local' => 'id',
             'foreign' => 'area_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}