<?php

/**
 * CategoryObjectTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoryObjectTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CategoryObjectTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CategoryObject');
    }
}