<?php

/**
 * CommentReportTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CommentReportTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CommentReportTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CommentReport');
    }
}