<?php

/**
 * DdAddressBookTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DdAddressBookTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DdAddressBookTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DdAddressBook');
    }
}