<?php

/**
 * DdClientTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DdClientTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DdClientTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DdClient');
    }
}