<?php

/**
 * DdPortfolioCommitTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DdPortfolioCommitTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DdPortfolioCommitTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DdPortfolioCommit');
    }
}