<?php

/**
 * DdPortfolioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DdPortfolioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DdPortfolioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DdPortfolio');
    }
}