<?php

/**
 * DdSkillTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DdSkillTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DdSkillTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DdSkill');
    }
}