<?php

/**
 * DdStatusTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DdStatusTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DdStatusTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DdStatus');
    }
}