<?php

/**
 * ScssScoutEnrollmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ScssScoutEnrollmentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ScssScoutEnrollmentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ScssScoutEnrollment');
    }
}