<?php

/**
 * ScssCampsiteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ScssCampsiteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ScssCampsiteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ScssCampsite');
    }
}