<?php

/**
 * ScssArea
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    scss
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ScssArea extends BaseScssArea
{
  public function getAreaSlug() { return $this->getSlug(); }
  public function getParentSlug() { return $this->getParent()->getSlug(); }
  public function getCampSlug() { return $this->getCamp()->getSlug(); }
  public function getDistrictSlug() { return $this->getCamp()->getDistrict()->getSlug(); }
}
