<?php

/**
 * ScssPeriodTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ScssPeriodTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ScssPeriodTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ScssPeriod');
    }
}