<?php

/**
 * ScssWeekTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ScssWeekTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ScssWeekTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ScssWeek');
    }

    public function getPeriods(Doctrine_Query $q=null) {
        if(is_null($q)) {
            $q = Doctrine_Query::create()
                ->from('ScssPeriod p');
        }
        $q->where('p.week_id = ?',sfContext::getInstance()->getUser()->getProfile()->getActiveEnrollment()->getWeek()->getId());

        return $q->execute();
    }
}