<?php

/**
 * ScssAddressBookTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ScssAddressBookTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ScssAddressBookTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ScssAddressBook');
    }
}