<?php

/**
 * ScssClass
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    scss
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ScssClass extends BaseScssClass
{
    public function getName() {
        return $this->getCourse()->getLabel();
    }
    public function __toString() {
        return $this->getCourse()->getLabel();
    }
    
    public function getCampSlug() { return $this->getPeriod()->getWeek()->getCamp()->getSlug(); }
    public function getWeekSlug() { return $this->getPeriod()->getWeek()->getSlug(); }
    public function getPeriodSlug() { return $this->getPeriod()->getSlug(); }
    public function getClassSlug() { return $this->getCourse()->getSlug(); }
    public function getDistrictSlug() { return $this->getPeriod()->getWeek()->getCamp()->getDistrict()->getSlug(); }
}
