<?php

/**
 * ScssClassTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ScssClassTable extends Doctrine_Table
{
    /**
   * Use custom query class
   */  
    public function construct() {
      $this->setAttribute(Doctrine::ATTR_QUERY_CLASS, 'ScssCampQuery');
    }
  
    /**
     * Returns an instance of this class.
     *
     * @return object ScssClassTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ScssClass');
    }

    public function retrieveForSelect($p,$q,$limit=20) {
        $q = Doctrine_Query::getTable('ScssClass')
                ->createQuery('c')
                ->filterByPeriod($p)
                ->leftJoin('c.MeritBadge m')
                ->orderBy('m.name ASC')
                ->limit($limit);
       $classes = array();
       foreach ($q->execute() as $class) {
           $classes[$class->getId()] = (string) $class->getCourse()->getMeritBadge()->getName();
       }
       return $classes;
    }
}