<?php

/**
 * ScssAreaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ScssAreaTable extends Doctrine_Table
{
  
    /**
   * Use custom query class
   */  
    public function construct() {
      $this->setAttribute(Doctrine::ATTR_QUERY_CLASS, 'ScssAreaQuery');
    } 
    
    /**
     * Returns an instance of this class.
     *
     * @return object ScssAreaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ScssArea');
    }
}