<?php

/**
 * ScssStaffTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ScssStaffTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ScssStaffTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ScssStaff');
    }
}