<?php

/**
 * ScssScoutTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ScssScoutTable extends Doctrine_Table
{
    /**
   * Use custom query class
   */  
    public function construct() {
      $this->setAttribute(Doctrine::ATTR_QUERY_CLASS, 'ScssScoutQuery');
    }  
    /**
     * Returns an instance of this class.
     *
     * @return object ScssScoutTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ScssScout');
    }

    public function addEnrolledQuery($w_id,Doctrine_Query $q)
    {
        return $r;
    }
    public function getFromRequest(sfWebRequest $r, Doctrine_Query $q = null) {
      if((!$slugs['district'] = $r->getParameter('district_slug')) ||
         (!$slugs['troop'] = $r->getParameter('troop_slug')) ||
         (!$slugs['scout'] = $r->getParameter('scout_slug'))) return false;
      if(is_null($q)) {
            $q = Doctrine_Query::create()
                ->from('ScssScout s')
                ->leftJoin('s.Patrol p')->leftJoin('p.Troop t')->leftJoin('t.District d');
        }
        $alias = $q->getRootAlias();
        $q->where('d.slug = ?', $slugs['district'])
                 ->andWhere('t.slug = ?',$slugs['troop'])
                 ->andWhere('s.slug = ?', $slugs['scout']);
      return $q->fetchOne();
    }
}