<?php

/**
 * ScssRequirementTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ScssRequirementTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ScssRequirementTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ScssRequirement');
    }
}