<?php

/**
 * ScssZoneTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ScssZoneTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ScssZoneTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ScssZone');
    }
}