<?php

/**
 * ScssPeriod
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    scss
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ScssPeriod extends BaseScssPeriod
{
	public function getName() {
	  return $this->getLabel();
  }

  public function getClasses() {
    $q = Doctrine_Core::getTable('ScssClass')->createQuery('l')
      ->where('l.period_id = ?',$this->getId());
    $r = $q->execute();
    return $r;
  }
}
