<?php

/**
 * ScssRankTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ScssRankTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ScssRankTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ScssRank');
    }
}