<?php

/**
 * ScssCourseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ScssCourseTable extends Doctrine_Table
{
    /**
   * Use custom query class
   */  
    public function construct() {
      $this->setAttribute(Doctrine::ATTR_QUERY_CLASS, 'ScssCourseQuery');
    }
    /**
     * Returns an instance of this class.
     *
     * @return object ScssCourseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ScssCourse');
    }
}