<?php

/**
 * ScssCampTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ScssCampTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ScssCampTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ScssCamp');
    }
    public static function limitByAccess($limit,Doctrine_Query $q = null) {
      if(is_null($q)) {
        $q = Doctrine_Query::create()
	  ->from('ScssCamp c');
      }
      $alias = $q->getRootAlias();
      switch($limit) {
        case SCSS::CAMP_ADMIN:
          $q->where('c.id = ?',$this->getUser()->getProfile()->getActivEnrollment()->getCamp()->getId());
          break;
        case SCSS::DISTRICT_ADMIN:
          $q->leftJoin('c.District d')->where('d.id = ?',$this->getUser()->getProfile()->getActiveEnrollment()->getCamp()->getDistrict()->getId());
          break;
      }   
      return $q;
    }
}
