<?php

/**
 * ScssStaffTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ScssStaffTable extends Doctrine_Table
{
    /**
   * Use custom query class
   */  
    public function construct() {
      $this->setAttribute(Doctrine::ATTR_QUERY_CLASS, 'ScssStaffQuery');
    }    
    /**
     * Returns an instance of this class.
     *
     * @return object ScssStaffTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ScssStaff');
    }
}