<?php

/**
 * ScssTroop
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    scss
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ScssTroop extends BaseScssTroop
{
    public function getPatrols() {
        $q = Doctrine::getTable('ScssPatrol')->createQuery('p')->where('p.troop_id = ?', $this->getId());
        $r = $q->execute();
        return $r;
    }
    public function getPatrolCount() {
        return $this->getPatrols()->count();
    }
    public function getScoutCount() {
        $p = $this->getPatrols();
        $c = 0;
        foreach($p as $_p) {
            $c += $_p->getScoutCount();
        }
        return $c;
    }
    public function getScouts() {
        $q = Doctrine::getTable('ScssScout')->createQuery('s')->leftJoin('s.Patrol p')->where('p.troop_id = ?',$this->getId());
        $r = $q->execute();
        return $r;
    }
    public function getName() {
	return $this->getNumber();
    }
}
