<?php

/**
 * ScssCourseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ScssCourseTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ScssCourseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ScssCourse');
    }
}