<?php

/**
 * ScssCabinTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ScssCabinTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ScssCabinTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ScssCabin');
    }
}