<?php

/**
 * ScssScout
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    scss
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ScssScout extends BaseScssScout
{
    public function __toString() {
        return $this->getFirstName().' '.$this->getLastName();
    }
    public function getName() { return $this; }
    public function getEnrollment($p=null,$w=null) {
        if(is_null($w)) $w = sfContext::getInstance()->getUser()->getProfile()->getActiveEnrollment()->getWeek()->getId();
        // build query
        $q = Doctrine::getTable('ScssScoutEnrollment')->createQuery('e')
                ->leftJoin('e.Class c')->leftJoin('c.Period p')
                ->where('e.scout_id = ?',$this->getId())
                ->andWhere('p.week_id = ?',$week);
        if(!is_null($p))    $q->andWhere('p.id = ?',$p);
        $q->orderBy('p.label ASC');
        $class = $q->execute();

        return (is_null($p) ? $class : $class[0]);
    }
    public function isEnrolled($week) {
      return (count($this->getEnrollments(null,$week->getId())) >= 1);
    }
    public function getScoutFromRequest(sfWebRequest $r) {
      if((!$slugs['district'] = $r->getParameter('district_slug')) ||
         (!$slugs['troop'] = $r->getParameter('troop_slug')) ||
         (!$slugs['scout'] = $r->getParameter('scout_slug'))) return false;
      $scout = Doctrine::getTable('ScssScout')->createQuery('s')
                 ->leftJoin('s.Patrol p')->leftJoin('p.Troop t')->leftJoin('t.District d')
                 ->where('d.slug = ?', $slugs['district'])
                 ->andWhere('t.slug = ?',$slugs['troop'])
                 ->andWhere('s.slug = ?', $slugs['scout'])->execute();
      return $scout[0];
    }
/* public function getClassByPeriodId($pid,$r_text=false) { // true will return label of class, false will return class id
        //echo "p:".$pid."<br/>"."s:".$this->getId();
        $q = Doctrine::getTable('ScssScoutEnrollment')
            ->createQuery('e')
            ->leftJoin('e.Class c')
            ->where('e.scout_id = ?',$this->getId())
            ->andWhere('c.period_id = ?',$pid);
        return   $q->fetchOne();
        //return $ret[0];
    }*/
}
