<?php

/**
 * ScssMeritBadgeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ScssMeritBadgeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ScssMeritBadgeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ScssMeritBadge');
    }
}