<?php

/**
 * ScssStaff
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    scss
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ScssStaff extends BaseScssStaff
{
	public function getName() {
	  return ucwords($this->getFirstName().' '.$this->getLastName());
	}
}
