<?php

/**
 * ScssClassTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ScssClassTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ScssClassTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ScssClass');
    }

    public function retrieveForSelect($p,$q,$limit=20) {
        $q = Doctrine_Query::create()
            ->from('ScssClass c')
            ->leftJoin('c.Course r')
            ->leftJoin('r.MeritBadge m')
            ->where('c.period_id = ?',$p)
            ->orderBy('m.name ASC')
            ->limit($limit);
       $classes = array();
       foreach ($q->execute() as $class) {
           $classes[$class->getId()] = (string) $class->getCourse()->getMeritBadge()->getName();
       }
       return $classes;
    }
}