<?php

/**
 * ScssPeriodTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ScssPeriodTable extends Doctrine_Table
{
    /**
   * Use custom query class
   */  
    public function construct() {
      $this->setAttribute(Doctrine::ATTR_QUERY_CLASS, 'ScssPeriodQuery');
    }  
    /**
     * Returns an instance of this class.
     *
     * @return object ScssPeriodTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ScssPeriod');
    }
}