<?php

/**
 * ScssDistrictTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ScssDistrictTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ScssDistrictTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ScssDistrict');
    }
}