<?php

/**
 * ScssSubRequirementTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ScssSubRequirementTable extends ScssRequirementTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ScssSubRequirementTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ScssSubRequirement');
    }
}