<?php

/**
 * ScssSubAreaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ScssSubAreaTable extends ScssAreaTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ScssSubAreaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ScssSubArea');
    }
}