<?php

/**
 * ScssActiveEnrollmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ScssActiveEnrollmentTable extends sfGuardUserProfileTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ScssActiveEnrollmentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ScssActiveEnrollment');
    }
}