<?php

/**
 * ScssTroopEnrollmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ScssTroopEnrollmentTable extends Doctrine_Table
{
  /**
   * Use custom query class
   */  
  public function construct() {
      $this->setAttribute(Doctrine::ATTR_QUERY_CLASS, 'ScssTroopEnrollmentQuery');
    }
    /**
     * Returns an instance of this class.
     *
     * @return object ScssTroopEnrollmentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ScssTroopEnrollment');
    }
    

}