<?php

/**
 * ScssPatrolTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ScssPatrolTable extends Doctrine_Table
{
    /**
   * Use custom query class
   */  
    public function construct() {
      $this->setAttribute(Doctrine::ATTR_QUERY_CLASS, 'ScssPatrolQuery');
    }  
    
    /**
     * Returns an instance of this class.
     *
     * @return object ScssPatrolTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ScssPatrol');
    }
}