<?php

/**
 * ScssTroopTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ScssTroopTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ScssTroopTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ScssTroop');
    }
    public function getPatrols(Doctrine_Query $q = null) {
        if(is_null($q)) {
            $q = Doctrine_Query::create()
            ->from('ScssPatrol p');
        }
        $alias = $q->getRootAlias();
        $q->andWhere($alias . '.troop_id = ?',sfContext::getInstance()->getUser()->getProfile()->getTroop()->getId());

        return $q->execute();
    }
    public function getScouts($forForm = false, Doctrine_Query $q = null) {
        if(is_null($q)) {
            $q = Doctrine_Query::create()
                ->from('ScssScout s')
                ->leftJoin('s.Patrol p');
        }
        $alias = $q->getRootAlias();
        $q->where('p.troop_id = ?', sfContext::getInstance()->getUser()->getProfile()->getActiveEnrollment()->getTroop()->getId())->orderBy('s.last_name, s.first_name ASC');
        if($forForm)    $q->select('s.last_name,s.first_name,s.id');
        return $q->execute();
    }
    public function getScoutsForForm(Doctrine_Query $q = null) {
        return $q->getScouts()->select('s.last_name,s.first_name,s.id');
    }
}