<?php

/**
 * ScssTroopRotationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ScssTroopRotationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ScssTroopRotationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ScssTroopRotation');
    }
}