<?php

/**
 * ScssPatrolTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ScssPatrolTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ScssPatrolTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ScssPatrol');
    }
}