<?php

/**
 * SfGuardGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SfGuardGroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SfGuardGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SfGuardGroup');
    }
}