<?php

/**
 * SfGuardUserGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SfGuardUserGroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SfGuardUserGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SfGuardUserGroup');
    }
}