<?php

/**
 * SfGuardRememberKeyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SfGuardRememberKeyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SfGuardRememberKeyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SfGuardRememberKey');
    }
}