<?php

/**
 * SfGuardUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SfGuardUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SfGuardUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SfGuardUser');
    }
}