<?php

/**
 * SfGuardForgotPasswordTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SfGuardForgotPasswordTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SfGuardForgotPasswordTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SfGuardForgotPassword');
    }
}