<?php

/**
 * SfGuardPermissionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SfGuardPermissionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SfGuardPermissionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SfGuardPermission');
    }
}