<?php

/**
 * SfGuardGroupPermissionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SfGuardGroupPermissionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SfGuardGroupPermissionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SfGuardGroupPermission');
    }
}