<?php

/**
 * SfGuardUserPermissionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SfGuardUserPermissionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SfGuardUserPermissionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SfGuardUserPermission');
    }
}