# Generated by Django 5.0.6 on 2024-07-21 23:57

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("faction", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="attendee",
            managers=[
                ("attendee", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="leader",
            managers=[
                ("leader", django.db.models.manager.Manager()),
            ],
        ),
    ]
