# Generated by Django 5.0.6 on 2024-07-26 01:02

import django.contrib.auth.models
import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("faction", "0002_alter_attendee_managers_alter_leader_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="attendee",
            managers=[
                ("attendee", django.db.models.manager.Manager()),
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="leader",
            managers=[
                ("leader", django.db.models.manager.Manager()),
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
