# Generated by Django 5.0.1 on 2024-02-10 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faction", "0003_faction_slug"),
        ("organization", "0002_organization_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faction",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="factions",
                to="organization.organization",
            ),
        ),
    ]
