# Generated by Django 5.0.6 on 2024-07-26 01:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("faction", "0003_alter_attendee_managers_alter_leader_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendee",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="faction",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="faction",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="leader",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
