# Generated by Django 5.0.1 on 2024-01-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="street2",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
