# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "precise64"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  # Boot with a GUI so you can see the screen. (Default is headless)
  # config.vm.boot_mode = :gui

  config.vm.host_name = "scss.vagrant.local"
  # Assign this VM to a host-only network IP, allowing you to access it
  # via the IP. Host-only networks can talk to the host machine as well as
  # any other machines on the same network, but cannot be accessed (through this
  # network interface) by any external networks.
  config.vm.network :hostonly, "192.168.200.10"

  # Assign this VM to a bridged network, allowing you to connect directly to a
  # network using the host's network device. This makes the VM appear as another
  # physical device on your network.
  #config.vm.network( :bridged, :bridge => 'en1: Wi-Fi (AirPort)' )

  # Forward a port from the guest to the host, which allows for outside
  # computers to access the VM, whereas host only networking does not.
  # config.vm.forward_port 80, 8080

  # Share an additional folder to the guest VM. The first argument is
  # an identifier, the second is the path on the guest to mount the
  # folder, and the third is the path on the host to the actual folder.
  # config.vm.share_folder "v-data", "/vagrant_data", "../data"
  config.vm.share_folder "sites-enabled", "/etc/apache2/sites-enabled", "sites-enabled", :create => true
  # Old setting
  #config.vm.share_folder "project", "/var/www/vhosts/local.vagrant.scss", "../", :create => true, :extra => "dmode=777,fmode=777"
  # Use NFS instead of VirtualBox's file sharing
  # See:  http://forum.symfony-project.org/viewtopic.php?f=32&t=52241
  config.vm.share_folder "project", "/var/www/vhosts/local.vagrant.scss", "../", :create => true, :nfs => (RUBY_PLATFORM =~ /linux/ or RUBY_PLATFORM =~ /darwin/)

  # Script to run once the machine boots up for the first time
  config.vm.provision :shell, :path => "provisioner.sh"
end