# Generated by Django 5.0.1 on 2024-01-21 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("course", "0001_initial"),
        ("enrollment", "0001_initial"),
        ("facility", "0002_initial"),
        ("faction", "0002_initial"),
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendeeenrollment",
            name="attendee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="faction.attendee"
            ),
        ),
        migrations.AddField(
            model_name="attendeeenrollment",
            name="quarters",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="facility.quarters"
            ),
        ),
        migrations.AddField(
            model_name="attendeeclassenrollment",
            name="attendee_enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="enrollment.attendeeenrollment",
            ),
        ),
        migrations.AddField(
            model_name="facilityclassenrollment",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="facility.department"
            ),
        ),
        migrations.AddField(
            model_name="facilityclassenrollment",
            name="facility_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="enrollment.facilityclass",
            ),
        ),
        migrations.AddField(
            model_name="attendeeclassenrollment",
            name="facility_class_enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="enrollment.facilityclassenrollment",
            ),
        ),
        migrations.AddField(
            model_name="facilityenrollment",
            name="facility",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="facility.facility"
            ),
        ),
        migrations.AddField(
            model_name="facilityclass",
            name="facility_enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="enrollment.facilityenrollment",
            ),
        ),
        migrations.AddField(
            model_name="factionenrollment",
            name="facility_enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="enrollment.facilityenrollment",
            ),
        ),
        migrations.AddField(
            model_name="factionenrollment",
            name="faction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="faction.faction"
            ),
        ),
        migrations.AddField(
            model_name="factionenrollment",
            name="quarters",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="facility.quarters"
            ),
        ),
        migrations.AddField(
            model_name="attendeeenrollment",
            name="faction_enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="enrollment.factionenrollment",
            ),
        ),
        migrations.AddField(
            model_name="facultyclassenrollment",
            name="facility_class_enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="enrollment.facilityclassenrollment",
            ),
        ),
        migrations.AddField(
            model_name="facultyclassenrollment",
            name="faculty",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="facility.faculty"
            ),
        ),
        migrations.AddField(
            model_name="leaderenrollment",
            name="faction_enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="enrollment.factionenrollment",
            ),
        ),
        migrations.AddField(
            model_name="leaderenrollment",
            name="leader",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="faction.leader"
            ),
        ),
        migrations.AddField(
            model_name="organizationcourse",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="course.course"
            ),
        ),
        migrations.AddField(
            model_name="facilityclass",
            name="organization_course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="enrollment.organizationcourse",
            ),
        ),
        migrations.AddField(
            model_name="organizationenrollment",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="organization.organization",
            ),
        ),
        migrations.AddField(
            model_name="organizationcourse",
            name="organization_enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="enrollment.organizationenrollment",
            ),
        ),
        migrations.AddField(
            model_name="facilityenrollment",
            name="organization_enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="enrollment.organizationenrollment",
            ),
        ),
        migrations.AddField(
            model_name="facilityclassenrollment",
            name="period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="enrollment.period"
            ),
        ),
        migrations.AddField(
            model_name="week",
            name="facility_enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="enrollment.facilityenrollment",
            ),
        ),
        migrations.AddField(
            model_name="period",
            name="week",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="enrollment.week"
            ),
        ),
    ]
