# Generated by Django 5.0.6 on 2024-08-18 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0002_alter_course_description_alter_course_image_and_more"),
        ("enrollment", "0002_alter_attendeeclassenrollment_description_and_more"),
        ("facility", "0005_facultyprofile_address_alter_facility_address"),
        ("faction", "0005_attendeeprofile_address_leaderprofile_address"),
        ("organization", "0002_alter_organization_description_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activeenrollment",
            options={
                "verbose_name": "Active Enrollment",
                "verbose_name_plural": "Active Enrollments",
            },
        ),
        migrations.AlterModelOptions(
            name="attendeeclassenrollment",
            options={
                "ordering": [
                    "attendee_enrollment__attendee__last_name",
                    "attendee_enrollment__attendee__first_name",
                ],
                "verbose_name": "Attendee Class Enrollment",
                "verbose_name_plural": "Attendee Class Enrollments",
            },
        ),
        migrations.AlterModelOptions(
            name="attendeeenrollment",
            options={
                "ordering": ["attendee__last_name", "attendee__first_name"],
                "verbose_name": "Attendee Enrollment",
                "verbose_name_plural": "Attendee Enrollments",
            },
        ),
        migrations.AlterModelOptions(
            name="facilityclass",
            options={
                "ordering": ["name"],
                "verbose_name": "Facility Class",
                "verbose_name_plural": "Facility Classes",
            },
        ),
        migrations.AlterModelOptions(
            name="facilityclassenrollment",
            options={
                "ordering": ["facility_class__name", "period__start"],
                "verbose_name": "Facility Class Enrollment",
                "verbose_name_plural": "Facility Class Enrollments",
            },
        ),
        migrations.AlterModelOptions(
            name="facilityenrollment",
            options={
                "ordering": ["start"],
                "verbose_name": "Facility Enrollment",
                "verbose_name_plural": "Facility Enrollments",
            },
        ),
        migrations.AlterModelOptions(
            name="factionenrollment",
            options={
                "ordering": ["start"],
                "verbose_name": "Faction Enrollment",
                "verbose_name_plural": "Faction Enrollments",
            },
        ),
        migrations.AlterModelOptions(
            name="facultyclassenrollment",
            options={
                "ordering": ["faculty__last_name", "faculty__first_name"],
                "verbose_name": "Faculty Class Enrollment",
                "verbose_name_plural": "Faculty Class Enrollments",
            },
        ),
        migrations.AlterModelOptions(
            name="facultyenrollment",
            options={
                "ordering": ["faculty__last_name", "faculty__first_name"],
                "verbose_name": "Faculty Enrollment",
                "verbose_name_plural": "Faculty Enrollments",
            },
        ),
        migrations.AlterModelOptions(
            name="leaderenrollment",
            options={
                "ordering": ["start"],
                "verbose_name": "Leader Enrollment",
                "verbose_name_plural": "Leader Enrollments",
            },
        ),
        migrations.AlterModelOptions(
            name="organizationcourse",
            options={
                "ordering": ["name"],
                "verbose_name": "Organization Course",
                "verbose_name_plural": "Organization Courses",
            },
        ),
        migrations.AlterModelOptions(
            name="organizationenrollment",
            options={
                "ordering": ["start"],
                "verbose_name": "Organization Enrollment",
                "verbose_name_plural": "Organization Enrollments",
            },
        ),
        migrations.AlterModelOptions(
            name="period",
            options={
                "ordering": ["start"],
                "verbose_name": "Period",
                "verbose_name_plural": "Periods",
            },
        ),
        migrations.AlterModelOptions(
            name="week",
            options={
                "ordering": ["start"],
                "verbose_name": "Week",
                "verbose_name_plural": "Weeks",
            },
        ),
        migrations.AlterUniqueTogether(
            name="activeenrollment",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="facultyenrollment",
            name="faculty_class_enrollments",
        ),
        migrations.AlterField(
            model_name="activeenrollment",
            name="attendee_enrollment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_attendee_enrollments",
                to="enrollment.attendeeenrollment",
                verbose_name="Attendee Enrollment",
            ),
        ),
        migrations.AlterField(
            model_name="activeenrollment",
            name="facility_enrollment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_facility_enrollments",
                to="enrollment.facilityenrollment",
                verbose_name="Facility Enrollment",
            ),
        ),
        migrations.AlterField(
            model_name="activeenrollment",
            name="faction_enrollment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_faction_enrollments",
                to="enrollment.factionenrollment",
                verbose_name="Faction Enrollment",
            ),
        ),
        migrations.AlterField(
            model_name="activeenrollment",
            name="faculty_enrollment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_faculty_enrollments",
                to="enrollment.facultyenrollment",
                verbose_name="Faculty Enrollment",
            ),
        ),
        migrations.AlterField(
            model_name="activeenrollment",
            name="leader_enrollment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_leader_enrollments",
                to="enrollment.leaderenrollment",
                verbose_name="Leader Enrollment",
            ),
        ),
        migrations.AlterField(
            model_name="activeenrollment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="active_enrollments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="attendeeclassenrollment",
            name="attendee_enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_enrollments",
                to="enrollment.attendeeenrollment",
                verbose_name="Attendee Enrollment",
            ),
        ),
        migrations.AlterField(
            model_name="attendeeclassenrollment",
            name="facility_class_enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendee_class_enrollments",
                to="enrollment.facilityclassenrollment",
                verbose_name="Facility Class Enrollment",
            ),
        ),
        migrations.AlterField(
            model_name="attendeeenrollment",
            name="attendee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendee_enrollments",
                to="faction.attendee",
                verbose_name="Attendee",
            ),
        ),
        migrations.AlterField(
            model_name="attendeeenrollment",
            name="faction_enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendee_enrollments",
                to="enrollment.factionenrollment",
                verbose_name="Faction Enrollment",
            ),
        ),
        migrations.AlterField(
            model_name="attendeeenrollment",
            name="quarters",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendee_enrollments",
                to="facility.quarters",
                verbose_name="Quarters",
            ),
        ),
        migrations.AlterField(
            model_name="facilityclass",
            name="facility_enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="facility_classes",
                to="enrollment.facilityenrollment",
                verbose_name="Facility Enrollment",
            ),
        ),
        migrations.AlterField(
            model_name="facilityclass",
            name="organization_course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="facility_classes",
                to="enrollment.organizationcourse",
                verbose_name="Organization Course",
            ),
        ),
        migrations.AlterField(
            model_name="facilityclassenrollment",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="facility_class_enrollments",
                to="facility.department",
                verbose_name="Department",
            ),
        ),
        migrations.AlterField(
            model_name="facilityclassenrollment",
            name="facility_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="enrollment.facilityclass",
                verbose_name="Facility Class",
            ),
        ),
        migrations.AlterField(
            model_name="facilityclassenrollment",
            name="period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="facility_class_enrollments",
                to="enrollment.period",
                verbose_name="Period",
            ),
        ),
        migrations.AlterField(
            model_name="facilityenrollment",
            name="facility",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="facility.facility",
                verbose_name="Facility",
            ),
        ),
        migrations.AlterField(
            model_name="facilityenrollment",
            name="organization_enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="facility_enrollments",
                to="enrollment.organizationenrollment",
                verbose_name="Organization Enrollment",
            ),
        ),
        migrations.AlterField(
            model_name="factionenrollment",
            name="faction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="faction_enrollments",
                to="faction.faction",
                verbose_name="Faction",
            ),
        ),
        migrations.AlterField(
            model_name="factionenrollment",
            name="quarters",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="faction_enrollments",
                to="facility.quarters",
                verbose_name="Quarters",
            ),
        ),
        migrations.AlterField(
            model_name="factionenrollment",
            name="week",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="faction_enrollments",
                to="enrollment.week",
                verbose_name="Week",
            ),
        ),
        migrations.AlterField(
            model_name="facultyclassenrollment",
            name="facility_class_enrollment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="faculty_class_enrollments",
                to="enrollment.facilityclassenrollment",
                verbose_name="Facility Class Enrollment",
            ),
        ),
        migrations.AlterField(
            model_name="facultyclassenrollment",
            name="faculty",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_enrollments",
                to="facility.faculty",
                verbose_name="Faculty",
            ),
        ),
        migrations.AlterField(
            model_name="facultyclassenrollment",
            name="faculty_enrollment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_enrollments",
                to="enrollment.facultyenrollment",
                verbose_name="Faculty Enrollment",
            ),
        ),
        migrations.AlterField(
            model_name="facultyenrollment",
            name="facility_enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="faculty_enrollments",
                to="enrollment.facilityenrollment",
                verbose_name="Facility Enrollment",
            ),
        ),
        migrations.AlterField(
            model_name="facultyenrollment",
            name="faculty",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="facility.faculty",
                verbose_name="Faculty",
            ),
        ),
        migrations.AlterField(
            model_name="facultyenrollment",
            name="quarters",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="faculty_enrollments",
                to="facility.quarters",
                verbose_name="Quarters",
            ),
        ),
        migrations.AlterField(
            model_name="leaderenrollment",
            name="faction_enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leader_enrollments",
                to="enrollment.factionenrollment",
                verbose_name="Faction Enrollment",
            ),
        ),
        migrations.AlterField(
            model_name="leaderenrollment",
            name="leader",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leader_enrollments",
                to="faction.leader",
                verbose_name="Leader",
            ),
        ),
        migrations.AlterField(
            model_name="leaderenrollment",
            name="quarters",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leader_enrollments",
                to="facility.quarters",
                verbose_name="Quarters",
            ),
        ),
        migrations.AlterField(
            model_name="organizationcourse",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organization_courses",
                to="course.course",
                verbose_name="Course",
            ),
        ),
        migrations.AlterField(
            model_name="organizationcourse",
            name="organization_enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="enrollment.organizationenrollment",
                verbose_name="Organization Enrollment",
            ),
        ),
        migrations.AlterField(
            model_name="organizationenrollment",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="organization.organization",
                verbose_name="Organization",
            ),
        ),
        migrations.AlterField(
            model_name="period",
            name="week",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="periods",
                to="enrollment.week",
                verbose_name="Week",
            ),
        ),
        migrations.AlterField(
            model_name="week",
            name="facility_enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weeks",
                to="enrollment.facilityenrollment",
                verbose_name="Facility Enrollment",
            ),
        ),
        migrations.AddConstraint(
            model_name="activeenrollment",
            constraint=models.UniqueConstraint(
                fields=("user", "attendee_enrollment"),
                name="unique_active_attendee_enrollment",
            ),
        ),
        migrations.AddConstraint(
            model_name="activeenrollment",
            constraint=models.UniqueConstraint(
                fields=("user", "leader_enrollment"),
                name="unique_active_leader_enrollment",
            ),
        ),
        migrations.AddConstraint(
            model_name="activeenrollment",
            constraint=models.UniqueConstraint(
                fields=("user", "faction_enrollment"),
                name="unique_active_faction_enrollment",
            ),
        ),
        migrations.AddConstraint(
            model_name="activeenrollment",
            constraint=models.UniqueConstraint(
                fields=("user", "faculty_enrollment"),
                name="unique_active_faculty_enrollment",
            ),
        ),
        migrations.AddConstraint(
            model_name="activeenrollment",
            constraint=models.UniqueConstraint(
                fields=("user", "facility_enrollment"),
                name="unique_active_facility_enrollment",
            ),
        ),
    ]
