# Generated by Django 5.0.1 on 2024-02-08 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enrollment", "0004_activeenrollment"),
        ("facility", "0006_alter_department_facility_alter_quarters_facility"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="activeenrollment",
            name="attendee_enrollment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="enrollment.attendeeenrollment",
            ),
        ),
        migrations.AddField(
            model_name="activeenrollment",
            name="leader_enrollment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="enrollment.leaderenrollment",
            ),
        ),
        migrations.AlterField(
            model_name="activeenrollment",
            name="facility_enrollment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="enrollment.facilityenrollment",
            ),
        ),
        migrations.AlterField(
            model_name="activeenrollment",
            name="faction_enrollment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="enrollment.factionenrollment",
            ),
        ),
        migrations.AlterField(
            model_name="activeenrollment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="active_enrollments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="FacultyEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "facility_enrollment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="enrollment.facilityenrollment",
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="facility.faculty",
                    ),
                ),
                (
                    "faculty_class_enrollments",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="enrollment.facultyclassenrollment",
                    ),
                ),
                (
                    "quarters",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="facility.quarters",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="activeenrollment",
            name="faculty_enrollment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="enrollment.facultyenrollment",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="activeenrollment",
            unique_together={
                ("user", "attendee_enrollment"),
                ("user", "facility_enrollment"),
                ("user", "faction_enrollment"),
                ("user", "faculty_enrollment"),
                ("user", "leader_enrollment"),
            },
        ),
    ]
