# Generated by Django 5.0.1 on 2024-02-09 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enrollment", "0005_activeenrollment_attendee_enrollment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="facultyclassenrollment",
            name="faculty_enrollment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="enrollment.facultyenrollment",
            ),
        ),
        migrations.AlterField(
            model_name="facultyclassenrollment",
            name="facility_class_enrollment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="enrollment.facilityclassenrollment",
            ),
        ),
        migrations.AlterField(
            model_name="facultyenrollment",
            name="facility_enrollment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="enrollment.facilityenrollment",
            ),
        ),
        migrations.AlterField(
            model_name="facultyenrollment",
            name="faculty_class_enrollments",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="enrollment.facultyclassenrollment",
            ),
        ),
    ]
