# Generated by Django 5.0.1 on 2024-02-10 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enrollment", "0006_facultyclassenrollment_faculty_enrollment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facultyenrollment",
            name="facility_enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="enrollment.facilityenrollment",
            ),
        ),
    ]
