# Generated by Django 5.0.1 on 2024-02-11 14:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enrollment", "0007_alter_facultyenrollment_facility_enrollment"),
        ("facility", "0009_facultyprofile_enrollments_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="factionenrollment",
            name="facility_enrollment",
        ),
        migrations.AddField(
            model_name="factionenrollment",
            name="description",
            field=models.TextField(default=" "),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="factionenrollment",
            name="end_timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="factionenrollment",
            name="name",
            field=models.CharField(
                default="faction enrollment <function now at 0x000002166CC01940>",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="factionenrollment",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name="factionenrollment",
            name="start_timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="factionenrollment",
            name="week",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="enrollment.week",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="leaderenrollment",
            name="description",
            field=models.TextField(default=" "),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="leaderenrollment",
            name="end_timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="leaderenrollment",
            name="name",
            field=models.CharField(
                default="leader enrollment <function now at 0x000002166CC01940>",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="leaderenrollment",
            name="quarters",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="facility.quarters",
            ),
        ),
        migrations.AddField(
            model_name="leaderenrollment",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name="leaderenrollment",
            name="start_timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="facilityenrollment",
            name="facility",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="facility.facility",
            ),
        ),
    ]
