# Generated by Django 5.0.1 on 2024-02-03 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menuitem",
            options={"ordering": ["menu", "parent__id", "id"]},
        ),
        migrations.RemoveField(
            model_name="menuitem",
            name="permission",
        ),
        migrations.RemoveField(
            model_name="menuitem",
            name="url",
        ),
        migrations.AddField(
            model_name="menuitem",
            name="permissions",
            field=models.ManyToManyField(blank=True, to="auth.permission"),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="url_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="title",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "permissions",
                    models.ManyToManyField(blank=True, to="auth.permission"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="menuitem",
            name="menu",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="pages.menu",
            ),
        ),
    ]
