# Generated by Django 5.0.1 on 2024-02-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0002_alter_menuitem_options_remove_menuitem_permission_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="url_params",
            field=models.JSONField(default=dict),
        ),
    ]
