# Generated by Django 5.0.1 on 2024-02-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0003_menuitem_url_params"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="visible_to",
            field=models.CharField(
                choices=[
                    ("all", "All"),
                    ("authenticated", "Authenticated"),
                    ("guest", "Guest"),
                ],
                default="all",
                max_length=20,
            ),
        ),
    ]
