# Generated by Django 5.0.1 on 2024-02-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0004_menuitem_visible_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="url_params",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
