# Generated by Django 5.0.1 on 2024-02-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0005_alter_menuitem_url_params"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menuitem",
            name="url_params",
        ),
        migrations.AddField(
            model_name="menuitem",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="menu_images/"),
        ),
    ]
