# Generated by Django 5.0.1 on 2024-02-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0006_remove_menuitem_url_params_menuitem_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="css_class",
            field=models.CharField(
                blank=True,
                help_text="CSS class for the menu item",
                max_length=100,
                null=True,
            ),
        ),
    ]
