# Generated by Django 5.0.1 on 2024-02-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0008_menuitem_image_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="url_params",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
