# Generated by Django 5.0.1 on 2024-02-03 23:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0009_menuitem_url_params"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menuitem",
            name="permissions",
        ),
    ]
