# Generated by Django 5.0.1 on 2024-02-07 00:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("pages", "0010_remove_menuitem_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="permissions",
            field=models.ManyToManyField(blank=True, to="auth.permission"),
        ),
    ]
