# Generated by Django 5.0.1 on 2024-02-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0011_menuitem_permissions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menuitem",
            options={"ordering": ["menus", "parent__id", "id"]},
        ),
        migrations.RemoveField(
            model_name="menuitem",
            name="menu",
        ),
        migrations.AddField(
            model_name="menu",
            name="items",
            field=models.ManyToManyField(related_name="menus", to="pages.menuitem"),
        ),
    ]
