# Generated by Django 5.0.1 on 2024-02-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_user_options_user_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="dashboard_config",
            field=models.JSONField(default=dict),
        ),
    ]
