# Generated by Django 5.0.6 on 2024-07-21 23:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_adminprofile"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
