# Generated by Django 5.0.6 on 2024-08-12 22:21

import address.models
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0003_auto_20200830_1851"),
        ("user", "0005_alter_user_managers_adminprofile_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminprofile",
            name="address",
            field=address.models.AddressField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="address.address",
            ),
        ),
    ]
