# Generated by Django 5.0.6 on 2024-08-18 16:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_adminprofile_address"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AdminProfile",
        ),
    ]
