# Generated by Django 5.0.6 on 2024-07-20 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("image", models.ImageField(upload_to="images/")),
                (
                    "abbreviation",
                    models.CharField(blank=True, max_length=25, null=True),
                ),
                ("max_depth", models.PositiveIntegerField(blank=True, default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="organization.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrganizationLabels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attendee_label", models.CharField(default="Attendee", max_length=50)),
                ("facility_label", models.CharField(default="Facility", max_length=50)),
                ("faction_label", models.CharField(default="Faction", max_length=50)),
                (
                    "sub_faction_label",
                    models.CharField(default="Sub-Faction", max_length=50),
                ),
                ("faculty_label", models.CharField(default="Faculty", max_length=50)),
                ("leader_label", models.CharField(default="Leader", max_length=50)),
                (
                    "faculty_quarters_label",
                    models.CharField(default="Faculty Quarters", max_length=50),
                ),
                (
                    "faction_quarters_label",
                    models.CharField(default="Faction Quarters", max_length=50),
                ),
                (
                    "leader_quarters_label",
                    models.CharField(default="Leader Quarters", max_length=50),
                ),
                (
                    "attendee_quarters_label",
                    models.CharField(default="Attendee Quarters", max_length=50),
                ),
                ("course_label", models.CharField(default="Course", max_length=50)),
                (
                    "facility_enrollment_label",
                    models.CharField(default="Facility Enrollment", max_length=50),
                ),
                (
                    "faction_enrollment_label",
                    models.CharField(default="Faction Enrollment", max_length=50),
                ),
                (
                    "leader_enrollment_label",
                    models.CharField(default="Leader Enrollment", max_length=50),
                ),
                (
                    "attendee_enrollment_label",
                    models.CharField(default="Attendee Enrollment", max_length=50),
                ),
                (
                    "attendee_class_enrollment_label",
                    models.CharField(
                        default="Attendee Class Enrollment", max_length=50
                    ),
                ),
                ("week_label", models.CharField(default="Week", max_length=50)),
                ("period_label", models.CharField(default="Period", max_length=50)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labels",
                        to="organization.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrganizationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("max_depth", models.PositiveIntegerField(default=3)),
                ("max_faction_depth", models.PositiveIntegerField(default=2)),
                (
                    "labels",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="organization.organizationlabels",
                    ),
                ),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="organization.organization",
                    ),
                ),
            ],
        ),
    ]
