<?php

namespace Scss\OrganizationBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SubGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubGroupRepository extends EntityRepository
{
}