# Generated by Django 5.0.6 on 2024-07-21 23:57

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="faculty",
            managers=[
                ("faculty", django.db.models.manager.Manager()),
            ],
        ),
    ]
