# Generated by Django 5.0.6 on 2024-07-26 01:02

import django.contrib.auth.models
import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0002_alter_faculty_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="faculty",
            managers=[
                ("faculty", django.db.models.manager.Manager()),
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
