# Generated by Django 5.0.1 on 2024-01-23 00:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0003_alter_facultyprofile_facility_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quarters",
            name="type",
            field=models.CharField(
                choices=[
                    ("faction", "Faction Quarters"),
                    ("leader", "Leader Quarters"),
                    ("attendee", "Attendee Quarters"),
                    ("faculty", "Faculty Quarters"),
                    ("other", "Other Quarters"),
                ],
                default="other",
                max_length=50,
            ),
        ),
    ]
