# Generated by Django 5.0.1 on 2024-01-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0004_alter_quarters_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name="facility",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name="quarters",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
