# Generated by Django 5.0.6 on 2024-08-12 22:21

import address.models
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0003_auto_20200830_1851"),
        (
            "facility",
            "0004_alter_department_description_alter_department_image_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="facultyprofile",
            name="address",
            field=address.models.AddressField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="address.address",
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="address",
            field=address.models.AddressField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="address.address",
            ),
        ),
    ]
