# Generated by Django 5.0.1 on 2024-02-01 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0005_department_slug_facility_slug_quarters_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="facility",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departments",
                to="facility.facility",
            ),
        ),
        migrations.AlterField(
            model_name="quarters",
            name="facility",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quarters",
                to="facility.facility",
            ),
        ),
    ]
