# Generated by Django 5.0.1 on 2024-02-10 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("facility", "0007_alter_facility_organization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facultyprofile",
            name="facility",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="faculty",
                to="facility.facility",
            ),
        ),
    ]
