# Generated by Django 5.0.1 on 2024-02-10 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enrollment", "0007_alter_facultyenrollment_facility_enrollment"),
        ("facility", "0008_alter_facultyprofile_facility"),
        ("organization", "0002_organization_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="facultyprofile",
            name="enrollments",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="enrollment.facultyenrollment",
            ),
        ),
        migrations.AlterField(
            model_name="facultyprofile",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="facWulty",
                to="organization.organization",
            ),
        ),
    ]
