# Generated by Django 5.0.1 on 2024-01-26 00:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0002_course_slug_requirement_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="requirements",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="courses_as_requirement",
                to="course.requirement",
            ),
        ),
    ]
