# Generated by Django 5.0.1 on 2024-02-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0003_alter_course_requirements"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="requirements",
            field=models.ManyToManyField(
                blank=True,
                related_name="courses_as_requirement",
                to="course.requirement",
            ),
        ),
    ]
