# Generated by Django 5.0.1 on 2024-02-10 20:05

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0005_alter_course_requirements"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="prerequisites",
            field=models.ManyToManyField(
                blank=True, related_name="leads_to", to="course.course"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
