<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/12/19 06:04:17

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=mysql.daviddurost.net;dbname=dd_scss2',
  'username' => 'ner0tic',
  'password' => 'gatorade',
  'name' => 'doctrine',
)),);
